---
title: "treatment transition matrix"
subtitle: "v1"
output: html_notebook
date: "2017 JAN 20"
---

# setup
```{r setup, include=FALSE, echo = FALSE }
# set knitr defaults
knitr::opts_chunk$set(echo = TRUE, fig.width=20, fig.height=10)
source("z_start.R") # initalize netezza DB, load core data
if(!exists("TABLE04SAS7BDAT")) load("./data/TABLE04SAS7BDAT.RData")
PATIENTS_AGE_REGION <- FILTER_PATIENTS_AGE_REGION(TABLE04SAS7BDAT, cohort = "children")
```

# compute transitions
## define filters
```{r}
# 1. select
obs <- 
  PATIENTS_AGE_REGION %>% 
  filter(SUBSTANCENAME != "", isAED == TRUE) %>% 
  select(ENROLID, IXDAYS, SUBSTANCENAME) %>%
  distinct()

obs$SUBSTANCENAME <- as.character(obs$SUBSTANCENAME)

# 2. sort
obs       <- obs[order(obs$ENROLID,obs$IXDAYS,obs$SUBSTANCENAME),]

obs$prev_ENROL <- c("")
obs$prev_ENROL[2:(nrow(obs))]    <- obs$ENROLID[1:(nrow(obs)-1)]

obs$current_ENROL <- obs$ENROLID
obs$next_ENROL <- ""
obs$next_ENROL[1:(nrow(obs)-1)]    <- obs$ENROLID[2:nrow(obs)]

obs$current_SUBST <- obs$SUBSTANCENAME
obs$next_SUBST <- ""
obs$next_SUBST[1:(nrow(obs)-1)]    <- obs$SUBSTANCENAME[2:nrow(obs)]

# flag duplicates within patient
obs$duplicate <- (obs$current_ENROL == obs$next_ENROL) & (obs$current_SUBST == obs$next_SUBST)

# flag first entry of a patients observation
obs$firstObs <- obs$current_ENROL != obs$prev_ENROL
obs$firstObs[1] <- TRUE

# flag last entry of a patients observation
obs$lastObs <- obs$current_ENROL != obs$next_ENROL

```

## drop rows by filter criterium
```{r}
# drop rows where obs$firstObs and obs$lastObs both are true 
# these are patients with only 1 treatment event -> can't have a transition
obs <- obs %>% filter(!(firstObs & lastObs))

# drop last observation, because obs$next_SUBST point to the next ENROLID
obs <- obs %>% filter(!(lastObs))

# drop duplicates, if it isn't the first observation
obs <- obs %>% filter(!(duplicate & !firstObs))
```

## compute + plot transition matrix
```{r}

# absolute
obs$current_SUBST <- paste("current",obs$current_SUBST)
obs$next_SUBST <- paste("next",obs$next_SUBST)
tm <- as.data.frame.matrix(table(obs$current_SUBST, obs$next_SUBST))

# order by col and rowsum
tm.rowsum <- as.numeric(rowSums(tm))
tm.colsum <- as.numeric(colSums(tm))

tm <- tm[order(tm.rowsum,decreasing = TRUE),]
tm <- tm[,order(tm.colsum,decreasing = TRUE)]

# add annotation rowsum 
row.names(tm) <- paste(row.names(tm),"n =",rowSums(tm))
colnames(tm) <- paste(colnames(tm),"n =",colSums(tm))

# %
tm <- apply(tm,1, FUN = function(x) round(x/sum(x),2)) %>% as.data.frame() %>% t()

# https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html
corrplot::corrplot(
  tm,
  is.corr = FALSE,
  tl.col = 1,
  method = "circle",
  outline = T, tl.cex = 1,
  tl.srt = 35
  )

```

